name: Deploy Trading App

on:
  push:
    branches:
      - prod
      - dev
    paths:
      - 'infrastructure/template.yaml'
      - 'backend/**'
      - 'frontend/**'
      - 'samconfig.toml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::863518431982:role/TradingDashboardDeployRole
          role-session-name: github-action-session
          aws-region: eu-west-1

      - name: Install dependencies for backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest 

      - name: Run tests
        run: PYTHONPATH=$PWD pytest backend/tests

      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli

      - name: Build SAM app
        run: sam build

      - name: Deploy SAM app
        run: sam deploy --config-env ${{ github.ref_name }}


      - name: Setup Node.js for frontend
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build and export frontend
        run: |
          npm run build
          npm run export
        working-directory: ./frontend
        env:
          NEXT_PUBLIC_POWER_API_URL: ${{ env.NEXT_PUBLIC_POWER_API_URL }}

      - name: Deploy frontend to S3
        run: |
          aws s3 sync ./frontend/out/ s3://power-dashboard-frontend --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} \
            --paths "/*"